add link to chartsjs-plugin-error-bars
chartjs/awesome pull request #3
Opened 2019-06-30 05:15 UTC by sgratzl

Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

add a link to the https://github.com/datavisyn/chartjs-plugin-error-bars plugin for rendering error-bars onto bar and line charts

![selection_037](https://user-images.githubusercontent.com/5220584/43774415-4ab5ae88-9a49-11e8-813d-48d607d45225.png)

2019-06-30 14:38 UTC, benmccann approved these changes

2019-07-26 19:47 UTC, simonbrunel requested changes
Hi @sgratzl, thank you for your submission. Same comment as your other PR, [the name of the plugin](https://github.com/datavisyn/chartjs-plugin-error-bars/blob/master/src/plugin.js#L29) doesn't follow [our guidelines](https://www.chartjs.org/docs/latest/developers/plugins.html#plugin-id), it should be: `id: 'error-bars'`.

Can you please address this issue?

2019-08-13 09:18 UTC, SeppPenner commented
@sgratzl I have created a pull request for this under https://github.com/datavisyn/chartjs-plugin-error-bars/pull/19.

2019-09-27 22:34 UTC, sgratzl commented
closing in favor of my improved version: https://github.com/sgratzl/chartjs-chart-error-bars

2019-09-27 22:34 UTC, closed without merging