add xdoc
chartjs/awesome pull request #33
Opened 2021-06-18 10:44 UTC by nschloe

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

[xdoc](https://github.com/nschloe/xdoc), a browser extension that lets you use Chart.js (and other nice things) on GitHub pages. I added a new section _Other_ because it wouldn't fit anywhere else, but I'll be happy to reorganize.

2021-12-05 17:01 UTC, kurkle commented
This would need to be rebased. @simonbrunel @etimberg any thoughts about the section and/or if this is something accepted here?

2021-12-05 17:40 UTC, etimberg commented
I think another section is fine

2021-12-05 18:13 UTC, simonbrunel requested changes
A new section is fine but I wouldn't call it "other". Maybe something like "Tools" is better?

2021-12-05 18:13 UTC, simonbrunel commented on README.md
> +
Inconsistent extra line.

2021-12-05 18:13 UTC, simonbrunel commented on README.md
> +### Other
Wrong sectioning, should be `##`

2021-12-05 18:13 UTC, simonbrunel commented on README.md
> + - [xdoc](https://github.com/nschloe/xdoc) - Browser extension for using Chart.js on GitHub
`nschloe/xdoc` redirects to `nschloe/xhub` where there is no mention of "xdoc". Should rename the link to `xhub`.

2021-12-06 17:52 UTC, nschloe commented
I've addressed the comment and reformatted the entry.

2021-12-28 18:18 UTC, LeeLenaleee approved these changes

2021-12-28 20:02 UTC, simonbrunel approved these changes

2021-12-28 20:46 UTC, kurkle approved these changes

2021-12-28 20:46 UTC, merged