Add link
chartjs/awesome pull request #56
Opened 2022-12-13 21:25 UTC by erossini

Awesome Contribution Checklist:

- [ ] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [ ] I have searched to ensure the suggested item doesn't exist on this list
- [ ] This PR contains only one item

### Please Describe Your Addition

2022-12-14 08:05 UTC, simonbrunel requested changes

2022-12-14 08:05 UTC, simonbrunel commented on README.md
> +   ! 3️⃣ ❕ | [ChartJs for Blazor](https://github.com/erossini/BlazorChartjs) | Blazor component to use ChartJs in Blazor applications
- first emoji is incorrect, should be ❕ (not !)
- name should be `BlazorChartjs` (not "ChartJs for Blazor")
- description could be just "Blazor" (as we have for React, Vue.js, Java, etc.

2022-12-14 11:24 UTC, simonbrunel approved these changes

2022-12-14 12:59 UTC, etimberg approved these changes

2022-12-19 19:54 UTC, kurkle approved these changes

2022-12-19 19:54 UTC, merged